### ISSUE TITLE
File generation

### ISSUE THREAD

**Issue by dev-awevo** [mirakl/magento2-seller-connector#2] opened 2020-05-05 08:40 UTC
Hello,

We have a problem with the generation of classes that you use in your module.
Magento version : 2.3.4
We are on the last instance of your module.

Our problem come from your class : Sales\Model\Create\Order
In this class, you use Magento\Quote\Model\ResourceModel\Quote\Address\RateFactory
When Magento is in production mode, it create this kind of files (Factory) in the generated folder.
In this case, the class isn't created at the deployment of the production mode but when Magento saw it needed.
We think it's created after because you dont use this Factory class as a variable to call create on but you call it with on Object manager and use the create after that.
In our case, we use an intermediate server to deploy the production mode and copy the result on the right server after to avoid the maintenance of the website during the deployment of a new release.
Unfortunatly, Magento doesn't have the permissions to write on the generated folder in the production server.
As the class isn't created on the deployment of the production mode, Magento can't create it after and we have an error when we try to import Mirakl Orders.

To solve the problem, if you want to keep the use of Object manager, we need you to don't use the Factory class but the "classic" class.
For exemple use 
Magento\Quote\Model\ResourceModel\Quote\Address\Rate
Instead of
Magento\Quote\Model\ResourceModel\Quote\Address\RateFactory
Is it possible to make this change to all class like that to solve our problem ?

**Comment by dev-awevo** [comment] 2020-05-12 16:41
Please can you try your module after running the following commands:

```
bin/magento c:f && rm -rf pub/static/* var/page_cache/* var/cache/* var/composer_home/* var/view_preprocessed/* generated/code/* generated/metadata/*
bin/magento deploy:mode:set production
```
or these commands if you are already in production mode
```
bin/magento c:f && rm -rf generated/code/* generated/metadata/*
bin/magento setup:di:compile
```

**Comment by jreinke** [comment] 2020-06-02 13:39
Hello,

Sorry for the late reply.
The `setup:di:compile` command is working well and your problem is only due to the non-writable permissions on the `generated/` folder.
The problem is that the object manager is used at several places and I don't think that all the issues you may encounter will be fixed by just calling this class directly.
Don't you have the possibility to make this folder writable with your hosting company?

Best,

Johann

**Comment by stedau** [comment] 2020-10-09 14:37
Hello,
we cannot share the generated file because it is strongly recommended by Magento to leave it only in reading mode.
We should find a solution, because in state we have to tamper with our deployments to be able to make your module work.
This is the only problem, no other module running under magento 2 requires this kind of behavior.

Do you have a real solution to bring us? because we can't make the file accessible otherwise we risk breaking the site completely.
It is not for nothing that magento recommends to lock this folder!

Thank you in advance for your answer.

**Comment by jreinke** [comment] 2020-10-16 09:19
Hello,

[v1.2.8](https://github.com/mirakl/magento2-seller-connector/releases/tag/v1.2.8) has just been released and fixes the bug.

Thank you.

**Closed by jreinke** 2020-10-16 09:19 UTC
